server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    # 数据文件约 3.2 MB，开启 gzip 后约 400 KB
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
    }
}